query sanityQuery {
  allProjects(sort: [{ order: ASC }]) {
    visibility,
    order,
    color,
    title,
    short_description,
    description,
    technologies,
    website_link,
    code_link,
    logo {
      asset {
        url
      }
    },
    thumbnail {
      asset {
        url
      }
    }
  }

  allSkills(sort: [{ order: ASC }]) {
    visibility,
    order,
		name,
    details,
    image {
      asset {
        url
      }
    }
  }
}
